
org_id: github-app-oauth-test-chiselstrike
project_name: dummy-repo
volume:
  create: true
  size: 10Gi
replicas: 1

chiseld:
  image: 976672264352.dkr.ecr.us-east-2.amazonaws.com/chiseld
  tag: latest
  api_port: 8080
  rpc_port: 50051
  health_port: 9090
  datapath: /var/data
  rust_log: info
  rust_backtrace: 0
  executor_threads: 1
  data_db_uri: sqlite://$(DATAPATH)/chiseld-data.db?mode=rwc
  metadata_db_uri: sqlite://$(DATAPATH)/chiseld-meta.db?mode=rwc
toolset:
  image: 976672264352.dkr.ecr.us-east-2.amazonaws.com/toolset
  tag: latest
