
org_id: github-app-oauth-test-chiselstrike
project_name: simple-chisel-test
volume:
  create: true
  size: 10Gi
replicas: 1
backend: sqlite
backend_port: 5433
secrets:
  server_uri: "https://dogfood-chiselstrike.chiselstrike.io/main/secrets"
  rotation: "feb22"
  key_path: "/var/secrets/key"
allowed_ips: "0.0.0.0/24"
chiseld:
  image: 976672264352.dkr.ecr.us-east-2.amazonaws.com/chiseld
  tag: v0.7.0
  api_port: 8080
  rpc_port: 50051
  health_port: 9090
  datapath: /var/data
  rust_log: info
  rust_backtrace: 0
  executor_threads: 1
toolset:
  image: 976672264352.dkr.ecr.us-east-2.amazonaws.com/toolset
  tag: v0.7.0
